version: '3.8'

services:

  
  nginx:
    image: docker.io/library/nginx:1.19.0
    ports:
      - "80:80"
    
    
    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    
  
  mysql:
    image: docker.io/library/mysql:5.7
    ports:
      - "8081:80"
    
    
    environment:
      
      - MYSQL_ROOT_PASSWORD=pwd-wordpress
      
      - MYSQL_DATABASE=wordpress
      
      - MYSQL_USER=usr-wordpress
      
    
    
  
  wordpress-1:
    image: docker.io/library/wordpress:5.4.2-php7.2-apache
    ports:
      - "8082:80"
    
    depends_on:
      
      - nginx
      
      - mysql
      
    
    
    
  
  
  master:
    image: locustio/locust
    ports:
     - "8080:8089"
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
      - ./files:/files
    command: -f /mnt/locust/locustfile.py --master -H http://192.168.0.112
  
  worker:
    image: locustio/locust
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
      - ./files:/files
    command: -f /mnt/locust/locustfile.py --worker --master-host master